---
title: "Homework 12"
author: "Max Wagner"
date: "April 20, 2016"
header-includes:
   - \usepackage{bbm}
output:
  pdf_document: default
  html_document:
    highlight: espresso
    theme: flatly
  word_document: default
---
***

##576.2

Having a policy where stock-out exists allows for a few things. Most importantly it allows the company to only stock items that they sell frequently. Items that are sold less frequently can be allowed to drop to 0 inventory. The storage cost would be lower as less items are being stored at a given time. 

One potential downside to stock-out models is that customers could become frustrated, and the company would lose their future business (loss of goodwill).

In figure 13.7, it runs as a stock-out where inventory can go to 0, and more will need to be ordered. A new order is not placed until someone wants that product. It also assumes that the order amount remains the same. Considering that the demands and orders seem to be on a regular basis, it may be more efficient for the company to keep the item in stock.

One potential model assuming that goodwill cost is more than storage costs could be:

$$ Q_{new} = Q + q_b $$

where Q = quantity, and $q_b$ is quantity on backorder.

##585.2

$$ f(x,y) = 3x^2 + 6xy + 7y^2 - 2x + 4y $$

$$ f'(x) = 6x + 6y - 2 $$

$$ f'(y) = 6x + 14y + 4 $$

Solving the above gives $x=\frac{13}{12}$ and $y=\frac{-3}{4}$

The second derivative is positive so we can accept the two values as minimums.

$$f''(x) = 6$$

$$f''(y) = 14$$

##591.5

$$ 8x^2 + 4yz - 16z + 600 + \lambda (4x^2 + y^2 + 4z^2 - 16) $$

gives...

$$ 16x + 8x \lambda = 0 $$

$$ 4z + 2y \lambda = 0 $$

$$ 4y - 16 + 8z \lambda = 0 $$

$$ 4x^2 + y^2 + 4z^2 - 16 = 0 $$

and from that...

$\lambda = -2$, $y = -4/3$, $z= -4/3$, $x = 4/3$

##599.5

I think the biggest issue with a system like this, from a political standpoint, is that limiting a fisherman based on a model they know nothing about could be troublesome. Additionally, a model that changes from year to year based on population is essentially being regulated by itself, meaning that a governing body of some sort would be in charge of the life and death of a species. It's a big moral gray area to begin with, and even more difficult to enforce on a large scale. 